options:
  auto-update: true
max-enchant-levels:
  sweeping: 5
  sharpness: 5
  silk_touch: 1
  mending: 1
  power: 5
  flame: 1
  infinity: 1
  punch: 5
  channeling: 5
  bane_of_arthropods: 5
  smite: 5
  depth_strider: 5
  efficiency: 5
  unbreaking: 5
  fire_aspect: 5
  frost_walker: 1
  knockback: 5